Sprint 7: Init & Tables
AndreiChenchik/practicum-ios-ImageFeed pull request #1
Opened 2022-09-24 07:49 UTC by AndreiChenchik

2022-10-15 20:13 UTC, ABashkirova requested changes
Привет! Нужно доработать)

2022-10-15 20:13 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +        isFavoriteView = UIImageView()
очень странный способ настраивать вьюшки, обычно все-таки используют лейзи и описывают всю настройку в начале класса
```
lazy var image: UIImageView = { 
let image = UIImageView() 
...
return image
}
```

2022-10-15 20:13 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +        imageView.contentMode = .scaleAspectFit
Все-таки scaleAspectFill судя по макетам

2022-10-15 20:13 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +            UIColor(colorAsset: .background).withAlphaComponent(0.9).cgColor
С прозрачными переходами будьте осторожны. Всегда берите базовый цвет в начале и конце, добавив прозрачности, например из прозрачного в белый, лучше UIColor.white.withAlphaComponent(0) вместо clear. 
Потому что clear это черный с прозрачностью 0, и интерполяция будет из черного к базовому происходить.

2022-10-15 20:13 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +        let end = CGPoint(x: 0, y: 0.5393)
тут не согласна, у макетов видно что не из нуля происходит прозрачность а из 0.25 в 0.75.

2022-10-15 20:13 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +//                equalTo: contentView.trailingAnchor, constant: -16),
Почему?  макетам не соответствует верстка 

<img width="543" alt="Screenshot 2022-10-15 at 23 54 59" src="https://user-images.githubusercontent.com/20269264/196005639-36a5a4f6-6788-4694-a864-778b9064e5a3.png">

2022-10-15 20:13 UTC, ABashkirova commented on ImageFeed/ImagesListViewController.swift
> +        let dateString = formatter.string(from: model.date)
Создание  DateFormatter очень [дорогая операция](https://sarunw.com/posts/how-expensive-is-dateformatter/). Обычно необходимые в приложении форматтеры инициализируют один раз. 

Этот же метод будет вызываться на каждое переиспользование ячейки. 

Все-таки советую не пренебрегать авторскими решениями, в них хорошие практики даются(возможно без внимания advanced деталям, но все же) 🙏

2022-10-16 16:42 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        isFavoriteView = UIImageView()
Да, согласен, мне почему-то вечером показалось что так чище, но теперь вижу, что странно. Тут наверно и лейзи не нужен, т.к. я их все равно на старте сразу закидываю в сабвью.

2022-10-16 16:48 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        isFavoriteView = UIImageView()
Исправил, спасибо за комментарий

2022-10-16 16:58 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        let end = CGPoint(x: 0, y: 0.5393)
Что-то мне кажется, там все сложнее, там видать леер был с горизонтальным градиентом, а потом ему сделали ротейт и заскейлили его, поэтому изначально то 0.25 и 0.75, но потом там пообще непойми что произошло, на скриншоте видно.
<img width="223" alt="image" src="https://user-images.githubusercontent.com/217896/196048084-7334f9c2-c8fc-4182-9768-4c06b3ed3ba1.png">

Поэтому я ориентировался на CSS версию, в которой все скомбинировано
<img width="256" alt="image" src="https://user-images.githubusercontent.com/217896/196048181-9208f968-ad18-4063-a51e-44c914294a47.png">

2022-10-16 16:59 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        let end = CGPoint(x: 0, y: 0.5393)
Прошу зачесть сие значение :) получается похоже на дизайн @ABashkirova

2022-10-16 17:01 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +            UIColor(colorAsset: .background).withAlphaComponent(0.9).cgColor
Ого, не знал, спасибо, коварный клир! Исправил :)

2022-10-16 17:04 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        imageView.contentMode = .scaleAspectFit
В целом наверно и не важно, если мы соблюдаем aspectRatio по заданию, т.е. у нас оно и не обрезается и поля не добавляются. Или я что-то не учитываю? @ABashkirova

2022-10-16 17:05 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +//                equalTo: contentView.trailingAnchor, constant: -16),
Потому что забыл пушнуть последний коммит :( Это было очень не просто. Теперь красиво 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/217896/196048489-595f889b-02cf-459e-aaca-f4a094e4023d.png">

2022-10-16 17:11 UTC, AndreiChenchik commented on ImageFeed/ImagesListViewController.swift
> +        let dateString = formatter.string(from: model.date)
Беда, действительно поспешил, спасибо большое за замечание! Исправлено

2022-10-16 17:14 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        imageView.contentMode = .scaleAspectFit
Вижу, что прям просят по заданию поставить Fill, так что я поставил, но что-то мне кажется это лишнее.

2022-10-16 18:07 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +        let end = CGPoint(x: 0, y: 0.5393)
Ну а что тут, 0 прозрачности у первого цвета, 20 - у другого. 

Вектор и правда, почему-то в самом градиенте посмотреть нельзя(обычно прям на градиент можно тыкнуть), но через генератор кода понятны точки, а то что координаты не те, ну это не сложно местами поменять методом тыка 

Имхо, ваше решение на глаз мне показалось жестковатым. 

Это задание не обязательное, поэтому то вы тут свободны решать за правильность :)

2022-10-16 18:08 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +        imageView.contentMode = .scaleAspectFit
Ну если у вас все ячейки 4 к 3 как в макетах, то aspect fit будет с полями для разных пикчей. Так что вполне играет роль

2022-10-16 18:09 UTC, ABashkirova commented on ImageFeed/ImagesListCell.swift
> +//                equalTo: contentView.trailingAnchor, constant: -16),
Ожидаю что-то такое:
![image](https://user-images.githubusercontent.com/20269264/196051089-d844c449-746f-41f3-af98-3f6f5b0b969c.png)

2022-10-16 18:12 UTC, ABashkirova approved these changes
Замечания минорные, думаю что здесь вы можете сами решить следовать им или нет :)

Успехов!

2022-10-16 18:12 UTC, ABashkirova commented on ImageFeed/ImagesListViewController.swift
> +        return cellHeight
Интересно конечно, да, это ок, но кажется все-таки по макету 4 к 3 🙃

2022-10-22 13:57 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        imageView.contentMode = .scaleAspectFit
@ABashkirova блин, если там фиксированный aspectRatio то это будет просто провалом с моей стороны, я так старался, чтобы он зависел от контента и оно само растягивалось, сворачивалось в зависимости от контента... Это конечно эпичный провал будет)) Я 80%+ времени на это потратил.

2022-10-22 13:58 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        imageView.contentMode = .scaleAspectFit
Жалко выпиливать, но оставлю наверно пока так ;D

2022-10-22 14:16 UTC, AndreiChenchik commented on ImageFeed/ImagesListCell.swift
> +        let end = CGPoint(x: 0, y: 0.5393)
Жестковатость я успел поправить, действительно, в первом варианте было не 0 -> 0.2, а 0 - 0.9, спасибо за замечание. 

В итоге решил сравнить используя картинку из дизайна. Вроде сходятся градиенты в такой конфигурации!

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/217896/197343974-2ae123c6-e286-456e-8293-6c158fba2a44.png">

<img width="506" alt="image" src="https://user-images.githubusercontent.com/217896/197343995-f14b1ab6-49d7-4fc9-8467-70b4e96b981a.png">

2022-10-22 14:16 UTC, AndreiChenchik commented on ImageFeed/ImagesListViewController.swift
> +        return cellHeight
Вообще не понимаю почему я вбил себе в голову, что высота должна быть динамической... :( Ну интересный челендж был!

2022-10-22 14:19 UTC, AndreiChenchik commented on ImageFeed/ImagesListViewController.swift
> +        return cellHeight
Буду мёрджить, спасибо за ревью! @ABashkirova

2022-10-22 14:21 UTC, merged