Sprint 11: Packages, Multithreading & Security
AndreiChenchik/practicum-ios-ImageFeed pull request #4
Opened 2022-11-12 08:15 UTC by AndreiChenchik

2022-11-12 16:59 UTC, AndreiChenchik commented
@ABashkirova привет, вот PR по 11 спринту, там пока платформа чет не работает и не принимает отправки :) Вдруг будет время посмотреть

2022-11-12 17:06 UTC, ABashkirova commented
@AndreiChenchik Привет! 
обязательно напиши в поддержку, там помогут разобраться

2022-11-16 19:42 UTC, ABashkirova requested changes
Комментарий на платформе

2022-11-16 19:42 UTC, ABashkirova commented on ImageFeed/Scenes/Profile/ProfileViewController.swift
> +            self, action: #selector(logoutPressed), for: .touchUpInside)
```suggestion
        logoutButton.addTarget(self, action: #selector(logoutPressed), for: .touchUpInside)
```

2022-11-16 19:42 UTC, ABashkirova commented on ImageFeed/Services/NetworkClient.swift
> +    ) -> URLSessionTask
Если переносишь параметры, то переноси каждые два. Кажется это более менее последовательно.
```suggestion
    @discardableResult func fetch(
        url: URL, 
        handler: @escaping (Result<Data, Error>) -> Void
    ) -> URLSessionTask
```

2022-11-16 19:42 UTC, ABashkirova commented on ImageFeed/Services/ObjectService.swift
> +        request: URLRequest, handler: @escaping (Result<Object, Error>) -> Void
опять второй параметр остался на той же строке) есть референс на такой стиль?

2022-11-16 19:42 UTC, ABashkirova commented on ImageFeed/Services/ObjectService.swift
> +                    )
Либо так, 
```suggestion
                    let object = try JSONDecoder().decode(Object.self, from: data)
```
либо так (мне не нравится):
```suggestion
                    let object = try JSONDecoder().decode(
                        Object.self, 
                        from: data
                    )
```

2022-11-19 14:09 UTC, AndreiChenchik commented
Ревью на платформе
---

Привет, Андрей!

Прежде всего приношу извинения за заминку: на этом спринте по техническим причинам не смогли взять работу вчера и проверить за сутки. Сейчас все поправили и я успела застолбить проверку :)

Код как всегда - хорош. Мне нравится использование дженериков в сетевых запросах (не видела еще материал спринта, но полагаю это собственная реализация).

Однако, подсвечу один момент – отступление от задач спринта увеличивает время проверки работы. Советую использовать рекомендуемый нейминг в ключевых сервисах, чтобы не возникло недопониманий и работу можно было честно проверить.

Именно по этой причине сейчас по всему чеклисту подробно:

1.  Устранено состояние гонки в OAuthService. Получившееся решение должно корректно отрабатываться в ситуациях, когда ✅
2.  Устранено состояние гонки c помощью блокировки UI ✅
3.  Сделан сетевой слой для экрана профиля. С технической точки зрения он состоит из двух сетевых запросов. Первый:
    
    -   добавлен новый сервис ProfileService; ❌
    -   в него добавлена функция fetchProfile, которая получает данные пользователя через запрос GET /me, используя Bearer Token; ❌
    -   с помощью этих данных мы обновляем лейблы на экране ProfileViewController;✅
    -   чтобы не показывать заглушки на экране профиля, мы перенесли получение данных профиля в splash-screen. Теперь всегда отображаем данные, актуальные на момент запуска.✅

Второй — получение публичной информации о пользователе GET /users/:username — URL для получения аватарки пользователя (profile\_image):

-   добавлен сервис ProfileImageService для получения URL аватарки пользователя; ❌ (реализация другая, нужны пояснения, чтобы засчитать)
-   добавлен Observer для уведомления ProfileImageService.DidChangeNotification. ❌

4.  Пока идёт загрузка данных профиля, показывается Splash Screen✅
5.  Для отображения аватарки пользователя использована библиотека Kingfisher. ✅
6.  В проект добавлен SwiftKeychainWrapper через SPM ✅
7.  При получении ошибки в сетевом запросе в SplashViewController нужно показать UIAlertController с заголовком «Что-то пошло не так(», подписью «Не удалось войти в систему» и кнопкой «Ок» для скрытия алерта.❌

Мне очень важно, чтобы было исправлено:

-   добавлены промежуточные сервисы для работы с профилем. Не очень круто оставлять сборку реквеста на вью контроллере, как раз эту работу можно поручить ProfileService, а он уже в свою очередь пусть дергает ObjectService. Обычно так и происходит: есть модель данных получаемая с сервера(DTO) и та, что удобна для отображения (ViewModel). Промежуточные сервисы и нужны чтобы запрашивать и мапать данные друг в друга :)
-   отображение сетевых ошибок: ну как так 🙃
-   по поводу загрузки картинки: судя по всему, реализована загрузка картинки сразу в первом запросе, по заданию – это чит, так как кажется авторы хотели отработать концепцию Observer'а. Я уточню этот момент завтра, но пока не засчитываю.

Что еще заметила:

модели с предыдущего урока используют CodingKeys, это стандартная практика, когда у бека данные имеют не консистентный неймниг (snake\_case, camelCase). Однако если известно в каком стиле возвращаются данные, ты можешь использовать преднастроенный Decoder с установленной стратегией([статья](https://medium.com/@rwbutler/supercharge-codable-by-implementing-a-json-key-decoding-strategy-a46fedacabc4)). Но так как я вижу некоторые модели, в которых имена сильно отличаются, то здесь этот подход не подойдет. Также с енкодерами/декодерами принято переиспользовать преднастроенные объекты, чтобы не создавать каждый раз новый. Но в данном проекте, пока пару лишних вызовов инициализаторов не стоят лишней оптимизации.

2022-11-19 15:18 UTC, AndreiChenchik commented on ImageFeed/Services/ObjectService.swift
> +        request: URLRequest, handler: @escaping (Result<Object, Error>) -> Void
уфф :D Это я просто сам себе мозги тереблю максимальной длиной строки и форматирую так чтобы просто влезло ;D могу представить, что читать сложнее, сейчас исправлю все

2022-11-19 15:21 UTC, AndreiChenchik commented on ImageFeed/Services/ObjectService.swift
> +        request: URLRequest, handler: @escaping (Result<Object, Error>) -> Void
Спасибо за комментарии!

2022-11-19 15:23 UTC, AndreiChenchik commented on ImageFeed/Services/ObjectService.swift
> +                    )
Исправил)

2022-11-19 15:23 UTC, AndreiChenchik commented on ImageFeed/Services/NetworkClient.swift
> +    ) -> URLSessionTask
Поправил!

2022-11-19 15:23 UTC, AndreiChenchik commented on ImageFeed/Scenes/Profile/ProfileViewController.swift
> +            self, action: #selector(logoutPressed), for: .touchUpInside)
Поправил!

2022-11-19 15:52 UTC, AndreiChenchik commented
@ABashkirova 
> Однако, подсвечу один момент – отступление от задач спринта увеличивает время проверки работы. Советую использовать рекомендуемый нейминг в ключевых сервисах, чтобы не возникло недопониманий и работу можно было честно проверить.

Постараюсь называть как дано в теории в следующем спринте, хотя конечно я уже достаточно далеко ушел от оригинальной идеи :( Надеюсь хотябы в след проекте не будет сторибордов.

2022-11-19 15:53 UTC, AndreiChenchik commented
> Мне нравится использование дженериков в сетевых запросах (не видела еще материал спринта, но полагаю это собственная реализация).

Это все в спринте было :) Возможно в немного другой структуре

2022-11-19 19:47 UTC, AndreiChenchik commented
> Однако если известно в каком стиле возвращаются данные, ты можешь использовать преднастроенный Decoder с установленной стратегией

Почитал, спасибо большое! Просто пушка!

2022-11-19 19:49 UTC, AndreiChenchik commented
@ABashkirova  Вроде все проблемные места поправил, буду отправлять. Я старался избегать паттерна синглтона и следовать описанными в теории правилами DI, так что немного все же отошел от решения, но не далеко и не сильно.

2022-11-20 07:42 UTC, ABashkirova commented on ImageFeed/Services/ProfileService.swift
> +    }
👍🏻

2022-11-20 07:52 UTC, ABashkirova commented on ImageFeed/Core/ObjectService.swift
> +protocol ObjectLoading {
Тут опять дело вкуса, но от слова Object сразу джава в голове всплывает)

Тут фетчится модель с бека, я бы использовала слова Model, ResultModel, ResponseModel

2022-11-20 10:50 UTC, AndreiChenchik commented on ImageFeed/Core/ObjectService.swift
> +protocol ObjectLoading {
Слышу "Джава" - перехожу на другую сторону улицы. Поменял :D 
Кстати "object" было в теории, там дженерик objectTask, так что и взял себе это.

2022-11-20 10:51 UTC, merged

2022-11-20 17:07 UTC, ABashkirova commented on ImageFeed/Core/ObjectService.swift
> +protocol ObjectLoading {
Авторы на столько сеньоры, что у них object из objc)